version: "3"

networks:
  reverseproxy:
    driver: bridge

services:
  host:
    image: traefik
    restart: always
    command: --api --docker
    networks:
      - reverseproxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml:ro
      - ./acme:/etc/traefik/acme
