version: "3"

networks:
  reverseproxy:
    external:
      name: traefik_reverseproxy

services:
  omnibus:
    image: 'gitlab/gitlab-ce'
    restart: always
    hostname: ${GITLAB_DOMAIN}
    networks:
      - reverseproxy
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${GITLAB_DOMAIN}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT};
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['registry_enabled'] = true
        registry_external_url 'https://${GITLAB_DOMAIN}:${GITLAB_REGISTRY_PORT}'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = '${GITLAB_SMTP_HOSTNAME}'
        gitlab_rails['smtp_port'] = ${GITLAB_SMTP_PORT}    
        gitlab_rails['smtp_user_name'] = '${GITLAB_SMTP_USERNAME}'
        gitlab_rails['smtp_password'] = '${GITLAB_SMTP_PASSWORD}'
        gitlab_rails['smtp_authentication'] = 'login'
        gitlab_rails['smtp_ssl'] = false
        gitlab_rails['smtp_force_ssl'] = false
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        gitlab_rails['gitlab_email_from'] = '${GITLAB_SMTP_USERNAME}'
        gitlab_rails['gitlab_email_reply_to'] = '${GITLAB_SMTP_USERNAME}'
    ports:
      - '${GITLAB_SSH_PORT}:22'
      - '${GITLAB_REGISTRY_PORT}:${GITLAB_REGISTRY_PORT}'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_reverseproxy"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${GITLAB_DOMAIN}"
    volumes:
      - '${VOLUMES_ROOT_PATH}/etc/gitlab:/etc/gitlab'
      - '${VOLUMES_ROOT_PATH}/var/log/gitlab:/var/log/gitlab'
      - '${VOLUMES_ROOT_PATH}/var/opt/gitlab:/var/opt/gitlab'
      - /var/run/docker.sock:/var/run/docker.sock

  multi-runner:
    image: gitlab/gitlab-runner
    restart: always
    volumes:
      - ./gitlab-runner:/etc/gitlab-runner
      - ${VOLUMES_ROOT_PATH}/gitlab-runner/cache:/cache
      - /var/run/docker.sock:/var/run/docker.sock 